/**
 * SJM
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.vm.bme.skylordsauctions.network.smj.model

/**
 * 
 * @param priceData 
 * @param id 
 */
data class HistoryResponse (

    val priceData: kotlin.Array<PriceData>? = null,
    val id: kotlin.String? = null
) {
}