/**
 * SJM
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.vm.bme.skylordsauctions.network.smj.model

/**
 * 
 * @param id 
 * @param currentPrice 
 * @param meanPrice 
 * @param minPrice 
 * @param maxPrice 
 */
data class NoteworthyPrices (

    val _id: kotlin.String? = null,
    val currentPrice: PriceData? = null,
    val meanPrice: PriceData? = null,
    val minPrice: PriceData? = null,
    val maxPrice: PriceData? = null
) {
}