/**
 * SJM
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.vm.bme.skylordsauctions.network.smj.model


/**
 * 
 * @param time 
 * @param price 
 */
data class PriceData (

    val time: Long = 0L,
    val price: Int = 0
) {
}