/**
 * Cardbase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.vm.bme.skylordsauctions.network.cardbase.model

import com.google.gson.annotations.SerializedName


/**
 * 
 * @param name 
 * @param type 
 * @param power 
 * @param order 
 * @param description 
 * @param era 
 */
data class Ability (

    @SerializedName("Name") val name: kotlin.String? = null,
    @SerializedName("Type") val type: kotlin.Int? = null,
    @SerializedName("Power") val power: kotlin.Int? = null,
    @SerializedName("Order") val order: kotlin.Int? = null,
    @SerializedName("Description") val description: kotlin.String? = null,
    @SerializedName("Era") val era: kotlin.Int? = null
) {
}