/**
 * Cardbase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.vm.bme.skylordsauctions.network.cardbase.model

import com.google.gson.annotations.SerializedName
import hu.vm.bme.skylordsauctions.network.NetworkConfig

data class Card (
    @SerializedName("Name") val name: kotlin.String? = null,
    @SerializedName("Rarity") val rarity: kotlin.Int? = null,
    @SerializedName("Cost") val cost: kotlin.Int? = null,
    @SerializedName("Edition") val edition: kotlin.Int? = null,
    @SerializedName("Type") val type: kotlin.Int? = null,
    @SerializedName("Color") val color: kotlin.Int? = null,
    @SerializedName("Affinity") val affinity: kotlin.Int? = null,
    @SerializedName("IsRanged") val isRanged: kotlin.Boolean? = null,
    @SerializedName("Defense") val defense: kotlin.Int? = null,
    @SerializedName("Offense") val offense: kotlin.Int? = null,
    @SerializedName("DefenseType") val defenseType: kotlin.Int? = null,
    @SerializedName("OffenseType") val offenseType: kotlin.Int? = null,
    @SerializedName("UnitCount") val unitCount: kotlin.Int? = null,
    @SerializedName("ChargeCount") val chargeCount: kotlin.Int? = null,
    @SerializedName("Category") val category: kotlin.String? = null,
    @SerializedName("Abilities") val abilities: kotlin.Array<Ability>? = null,
    @SerializedName("Upgrades") val upgrades: kotlin.Array<Upgrade>? = null,
    @SerializedName("OrbInfo") val orbInfo: OrbInfo? = null,
    @SerializedName("Extra") val extra: kotlin.String? = null,
    @SerializedName("Image") val image: Image? = null
) {
    lateinit var smjId: String

    val imageUrl
        get() = "${NetworkConfig.imageBaseUrl}${image?.url}"
}