/**
 * Cardbase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.vm.bme.skylordsauctions.network.cardbase.model

import com.google.gson.annotations.SerializedName

/**
 * 
 * @param exception 
 * @param result 
 * @param success 
 */
data class CardbaseResult (
    @SerializedName("Exception") val exception: kotlin.String? = null,
    @SerializedName("Result") val result: kotlin.Array<Card>? = null,
    @SerializedName("Success") val success: kotlin.Boolean? = null
) {
}