/**
 * Cardbase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.vm.bme.skylordsauctions.network.cardbase.model

import com.google.gson.annotations.SerializedName


/**
 * 
 * @param name 
 * @param type 
 * @param collection 
 * @param cache 
 * @param maxAge 
 * @param url 
 * @param objectID 
 */
data class Image (
    @SerializedName("Name") val name: kotlin.String? = null,
    @SerializedName("Type") val type: kotlin.String? = null,
    @SerializedName("Collection") val collection: kotlin.String? = null,
    @SerializedName("Cache") val cache: kotlin.Boolean? = null,
    @SerializedName("MaxAge") val maxAge: kotlin.Int? = null,
    @SerializedName("Url") val url: kotlin.String? = null,
    @SerializedName("ObjectID") val objectID: kotlin.String? = null
) {
}