/**
 * Cardbase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.vm.bme.skylordsauctions.network.cardbase.model


/**
 * 
 * @param name 
 * @param difficulty 
 */
data class Map (

    val name: kotlin.String? = null,
    val difficulty: kotlin.Int? = null
) {
}