/**
 * Cardbase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.vm.bme.skylordsauctions.network.cardbase.model

import com.google.gson.annotations.SerializedName


/**
 * 
 * @param orbCode 
 * @param neutral 
 * @param frost 
 * @param fire 
 * @param nature 
 * @param shadow 
 */
data class OrbInfo (

    @SerializedName("OrbCode") val orbCode: kotlin.String? = null,
    @SerializedName("Neutral") val neutral: kotlin.Int? = null,
    @SerializedName("Frost") val frost: kotlin.Int? = null,
    @SerializedName("Fire") val fire: kotlin.Int? = null,
    @SerializedName("Nature") val nature: kotlin.Int? = null,
    @SerializedName("Shadow") val shadow: kotlin.Int? = null
) {
}